# Utilisez l'image officielle Node.js comme image de base
FROM node:20

# Définissez le répertoire de travail à l'intérieur du conteneur
WORKDIR /app

# Copiez le package.json et le package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez le reste de votre application dans le répertoire de travail
COPY . .

RUN npm run build

# Exposez le port sur lequel votre application écoute (par exemple, 3000)
EXPOSE 8001

# Démarrez votre application lorsque le conteneur démarre
# Point d'entrée de l'appliation : index.js
CMD [ "node", "dist/index.js" ] 
