import { LiveGame } from "./models/LiveGame";

export const persistantLiveGame = {
  gameId: 6665128255,
  gameType: "MATCHED_GAME",
  gameStartTime: 1699267098378,
  mapId: 11,
  gameLength: 302,
  platformId: "EUW1",
  gameMode: "CLASSIC",
  bannedChampions: [
    {
      pickTurn: 1,
      championId: 360,
      teamId: 100,
    },
    {
      pickTurn: 2,
      championId: 34,
      teamId: 100,
    },
    {
      pickTurn: 3,
      championId: 7,
      teamId: 100,
    },
    {
      pickTurn: 4,
      championId: 497,
      teamId: 100,
    },
    {
      pickTurn: 5,
      championId: 555,
      teamId: 100,
    },
    {
      pickTurn: 6,
      championId: 119,
      teamId: 200,
    },
    {
      pickTurn: 7,
      championId: 53,
      teamId: 200,
    },
    {
      pickTurn: 8,
      championId: 498,
      teamId: 200,
    },
    {
      pickTurn: 9,
      championId: 9,
      teamId: 200,
    },
    {
      pickTurn: 10,
      championId: 24,
      teamId: 200,
    },
  ],
  gameQueueConfigId: 420,
  participants: [
    {
      championId: 267,
      perks: {
        perkIds: [8214, 8226, 8234, 8237, 8347, 8304, 5008, 5008, 5002],
        perkStyle: 8200,
        perkSubStyle: 8300,
      },
      profileIconId: 6337,
      bot: false,
      teamId: 100,
      summonerName: "La lupa",
      summonerId: "_NlTZzjx2WHtxzaKUvadmreVdiOUaNqUcUXVkG3BHayQ_-s",
      spell1Id: 14,
      spell2Id: 4,
      porofessorStats: {
        name: "La lupa",
        id: "76947193",
        level: 710,
        role: {
          role: "support",
          mainRole: ["support"],
        },
        rankedStats: {
          division: null,
          gameAmount: 627,
          lp: 267,
          rank: "master",
          seasonId: "13.2",
          winrate: 50,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "master",
          seasonId: "13.1",
        },
        championStats: {
          name: "nami",
          winrate: 61,
          gameAmount: 38,
          kills: 1.4,
          deaths: 6.1,
          assists: 14.8,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 2.92 kills+assists en moyenne à 10 minutes quand il joue Nami",
          },
          {
            title: "Super Nami",
            value: "good",
            details: "Rang # 326 avec Nami % win (Classées): 60.5%",
          },
          {
            title: "Laner vulnérable",
            value: "bad",
            details:
              "Ce joueur a en moyenne seulement 1.74 morts à 10 minutes quand il joue Nami",
          },
        ],
      },
      masteries: {
        progression: 32.44,
        championProgression: 100,
        totalPoint: 6412821,
        championPoint: 252802,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "409fd1a9-2ec4-4f1d-bf5e-1d4e78daedbf",
          summonerId: "_NlTZzjx2WHtxzaKUvadmreVdiOUaNqUcUXVkG3BHayQ_-s",
          summonerName: "La lupa",
          queueType: "RANKED_FLEX_SR",
          tier: "EMERALD",
          rank: "I",
          leaguePoints: 19,
          wins: 130,
          losses: 128,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "_NlTZzjx2WHtxzaKUvadmreVdiOUaNqUcUXVkG3BHayQ_-s",
          summonerName: "La lupa",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 267,
          wins: 314,
          losses: 313,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 39,
      perks: {
        perkIds: [8010, 9111, 9105, 8299, 8304, 8345, 5005, 5008, 5003],
        perkStyle: 8000,
        perkSubStyle: 8300,
      },
      profileIconId: 3102,
      bot: false,
      teamId: 100,
      summonerName: "LARSAH4N",
      summonerId: "CkreurtqeWw7Oop2UXIiVQHv_hUfU9b7UXMNGLy456lHLIU",
      spell1Id: 4,
      spell2Id: 12,
      porofessorStats: {
        name: "LARSAH4N",
        id: "340853202",
        level: 297,
        role: {
          role: "mid",
          mainRole: ["mid"],
        },
        rankedStats: {
          division: null,
          gameAmount: 304,
          lp: 142,
          rank: "master",
          seasonId: "13.2",
          winrate: 51,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "master",
          seasonId: "13.1",
        },
        championStats: {
          name: "irelia",
          winrate: 49,
          gameAmount: 57,
          kills: 7.7,
          deaths: 6.9,
          assists: 5,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 2.89 kills+assists en moyenne à 10 minutes quand il joue Irelia",
          },
          {
            title: "<3 Irelia",
            value: "good",
            details:
              "a joué 57 parties avec Irelia durant les 30 derniers jours",
          },
          {
            title: "Bonne vision",
            value: "good",
            details:
              "Ce joueur a un haut score de vision par minute quand il joue Irelia (top 23.3% )",
          },
          {
            title: "1ère partie",
            value: "neutral",
            details: "Première partie aujourd'hui",
          },
          {
            title: "Split Pusher",
            value: "neutral",
            details: "Ce joueur split push très souvent quand il joue Irelia",
          },
          {
            title: "Laner vulnérable",
            value: "bad",
            details:
              "Ce joueur a en moyenne seulement 1.70 morts à 10 minutes quand il joue Irelia",
          },
        ],
      },
      masteries: {
        progression: 28.65,
        championProgression: 100,
        totalPoint: 4040262,
        championPoint: 366757,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "CkreurtqeWw7Oop2UXIiVQHv_hUfU9b7UXMNGLy456lHLIU",
          summonerName: "LARSAH4N",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 142,
          wins: 154,
          losses: 150,
          hotStreak: false,
          veteran: false,
          freshBlood: true,
          inactive: false,
        },
      ],
    },
    {
      championId: 20,
      perks: {
        perkIds: [8230, 8275, 8234, 8232, 9105, 9101, 5005, 5008, 5001],
        perkStyle: 8200,
        perkSubStyle: 8000,
      },
      profileIconId: 6285,
      bot: false,
      teamId: 100,
      summonerName: "Resuscitated",
      summonerId: "jtJJDJmVS-QqAu5HC2xCeBfR7JQ_1MLXMp-fLTzlulfHUs4",
      spell1Id: 4,
      spell2Id: 11,
      porofessorStats: {
        name: "Resuscitated",
        id: "57723551",
        level: 332,
        role: {
          role: "jungler",
          mainRole: ["jungler"],
        },
        rankedStats: {
          division: null,
          gameAmount: 207,
          lp: 183,
          rank: "master",
          seasonId: "13.2",
          winrate: 51,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "grandmaster",
          seasonId: "13.1",
        },
        championStats: {
          name: "nunu et willump",
          winrate: 41,
          gameAmount: 37,
          kills: 4.4,
          deaths: 4.6,
          assists: 10.6,
        },
        tags: [
          {
            title: "<3 Nunu et Willump",
            value: "good",
            details:
              " parties avec Nunu et Willump durant les 30 derniers jours",
          },
          {
            title: "Voleur",
            value: "good",
            details:
              "Ce joueur vole souvent l'hérald, le dragon ou le baron ( 0.16 par match) lorsqu'il joue Nunu et Willump",
          },
          {
            title: "1ère partie",
            value: "neutral",
            details: "Première partie aujourd'hui",
          },
        ],
      },
      masteries: {
        progression: 11.26,
        championProgression: 100,
        totalPoint: 1483147,
        championPoint: 657815,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "jtJJDJmVS-QqAu5HC2xCeBfR7JQ_1MLXMp-fLTzlulfHUs4",
          summonerName: "Resuscitated",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 183,
          wins: 106,
          losses: 101,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
        {
          leagueId: "92f10b07-3236-321c-86d0-7c9d2a0311c1",
          summonerId: "jtJJDJmVS-QqAu5HC2xCeBfR7JQ_1MLXMp-fLTzlulfHUs4",
          summonerName: "Resuscitated",
          queueType: "RANKED_FLEX_SR",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 61,
          wins: 19,
          losses: 12,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 897,
      perks: {
        perkIds: [8437, 8446, 8473, 8242, 8313, 8345, 5005, 5002, 5002],
        perkStyle: 8400,
        perkSubStyle: 8300,
      },
      profileIconId: 7,
      bot: false,
      teamId: 100,
      summonerName: "Takamura Teacher",
      summonerId: "qQ-j4nDRma_qsQ264NJCFEoDV3YjEjYgqzIiZOUCMUPhOZjVwpDMDw8plg",
      spell1Id: 12,
      spell2Id: 4,
      porofessorStats: {
        name: "Takamura Teacher",
        id: "406601830",
        level: 70,
        role: {
          role: "top",
          mainRole: ["top"],
        },
        rankedStats: {
          division: null,
          gameAmount: 345,
          lp: 204,
          rank: "master",
          seasonId: "13.2",
          winrate: 51,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "master",
          seasonId: "13.1",
        },
        championStats: {
          name: "k'santé",
          winrate: 67,
          gameAmount: 6,
          kills: 4.2,
          deaths: 7.5,
          assists: 5.2,
        },
        tags: [
          {
            title: "Split Pusher",
            value: "neutral",
            details: "Ce joueur split push très souvent quand il joue K'Santé",
          },
          {
            title: "Faible participation",
            value: "bad",
            details:
              "Ce joueur a une faible participation aux kills de l'équipe (est dans les 23.9% pires avec K'Santé )",
          },
          {
            title: "Main banni",
            value: "bad",
            details: "L'un des mains de ce joueur a été banni : Jax",
          },
        ],
      },
      masteries: {
        progression: 2.89,
        championProgression: 10.766203703703704,
        totalPoint: 301839,
        championPoint: 4651,
        championLevel: 2,
        championToken: 0,
        chestGranded: false,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId:
            "qQ-j4nDRma_qsQ264NJCFEoDV3YjEjYgqzIiZOUCMUPhOZjVwpDMDw8plg",
          summonerName: "Takamura Teacher",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 204,
          wins: 177,
          losses: 168,
          hotStreak: true,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 81,
      perks: {
        perkIds: [8010, 8009, 9103, 8014, 8345, 8304, 5005, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8300,
      },
      profileIconId: 3150,
      bot: false,
      teamId: 100,
      summonerName: "heαrt1",
      summonerId: "z3NUyBunJirnihR1zLhz4sjukBdgZDAXknEp_QOxg3Gvs00",
      spell1Id: 4,
      spell2Id: 3,
      porofessorStats: {
        name: "heαrt1",
        id: "31339539",
        level: 456,
        role: {
          role: "adc",
          mainRole: ["adc", " mid"],
        },
        rankedStats: {
          division: null,
          gameAmount: 122,
          lp: 166,
          rank: "master",
          seasonId: "13.2",
          winrate: 54,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "challenger",
          seasonId: "13.1",
        },
        championStats: {
          name: "ezreal",
          winrate: 44,
          gameAmount: 9,
          kills: 7.2,
          deaths: 5,
          assists: 5.6,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 3.00 kills+assists en moyenne à 10 minutes quand il joue Ezreal",
          },
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 12.1% meilleurs CSer avec Ezreal",
          },
        ],
      },
      masteries: {
        progression: 26.67,
        championProgression: 100,
        totalPoint: 3444804,
        championPoint: 330327,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "z3NUyBunJirnihR1zLhz4sjukBdgZDAXknEp_QOxg3Gvs00",
          summonerName: "heαrt1",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 166,
          wins: 66,
          losses: 56,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
        {
          leagueId: "92f10b07-3236-321c-86d0-7c9d2a0311c1",
          summonerId: "z3NUyBunJirnihR1zLhz4sjukBdgZDAXknEp_QOxg3Gvs00",
          summonerName: "heαrt1",
          queueType: "RANKED_FLEX_SR",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 119,
          wins: 36,
          losses: 29,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 29,
      perks: {
        perkIds: [8008, 8009, 9104, 8014, 8139, 8135, 5005, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8100,
      },
      profileIconId: 935,
      bot: false,
      teamId: 200,
      summonerName: "l3aal",
      summonerId: "1OXCsVCiDOMl2IJg5j1_wD8yzTHjrAFdpg1dniJ3NjKo1go",
      spell1Id: 6,
      spell2Id: 4,
      porofessorStats: {
        name: "l3aal",
        id: "21933645",
        level: 240,
        role: {
          role: "adc",
          mainRole: ["mid", " adc"],
        },
        rankedStats: {
          division: null,
          gameAmount: 413,
          lp: 172,
          rank: "master",
          seasonId: "13.2",
          winrate: 52,
        },
        previousSeasonRankedStats: {
          division: 2,
          rank: "diamant",
          seasonId: "13.1",
        },
        championStats: {
          name: "twitch",
          winrate: 61,
          gameAmount: 28,
          kills: 9,
          deaths: 5.3,
          assists: 7.6,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 2.86 kills+assists en moyenne à 10 minutes quand il joue Twitch",
          },
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 20.3% meilleurs CSer avec Twitch",
          },
          {
            title: "<3 Twitch",
            value: "good",
            details:
              "a joué 28 parties avec Twitch durant les 30 derniers jours",
          },
          {
            title: "Roam beaucoup",
            value: "neutral",
            details: "Ce joueur roams souvent quand il joue Twitch",
          },
        ],
      },
      masteries: {
        progression: 15.33,
        championProgression: 64,
        totalPoint: 1253895,
        championPoint: 42587,
        championLevel: 5,
        championToken: 2,
        chestGranded: false,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "1OXCsVCiDOMl2IJg5j1_wD8yzTHjrAFdpg1dniJ3NjKo1go",
          summonerName: "l3aal",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 172,
          wins: 216,
          losses: 197,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 62,
      perks: {
        perkIds: [8010, 9111, 9104, 8299, 8473, 8451, 5008, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8400,
      },
      profileIconId: 6231,
      bot: false,
      teamId: 200,
      summonerName: "akaAgusto",
      summonerId: "hUm1mL3nLwm2N4ZXXw_uFT9CUz0rEVZRwS3Q8oa3Tz-bfJHG29URD-vzOA",
      spell1Id: 4,
      spell2Id: 12,
      porofessorStats: {
        name: "akaAgusto",
        id: "435040731",
        level: 80,
        role: {
          role: "top",
          mainRole: ["top"],
        },
        rankedStats: {
          division: null,
          gameAmount: 262,
          lp: 216,
          rank: "master",
          seasonId: "13.2",
          winrate: 49,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "master",
          seasonId: "13.1",
        },
        championStats: {
          name: "wukong",
          winrate: 50,
          gameAmount: 74,
          kills: 5,
          deaths: 4.8,
          assists: 5.4,
        },
        tags: [
          {
            title: "Destructeurs de tours",
            value: "good",
            details:
              "Ce joueur inflige beaucoup de dégâts aux tours ( 18.4% meilleurs dégâts aux tours avec Wukong )",
          },
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 24.8% meilleurs CSer avec Wukong",
          },
          {
            title: "<3 Wukong",
            value: "good",
            details:
              "a joué 74 parties avec Wukong durant les 30 derniers jours",
          },
          {
            title: "OTP Wukong",
            value: "good",
            details:
              "Ce joueur ne joue quasiment que Wukong ( 93 % des parties des 30 derniers jours)",
          },
          {
            title: "Mauvais vs K'Santé",
            value: "bad",
            details:
              "Ce joueur a un winrate de 25% quand il joue Wukong contre K'Santé (sur 4 parties)",
          },
        ],
      },
      masteries: {
        progression: 1.8,
        championProgression: 100,
        totalPoint: 281561,
        championPoint: 185434,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId:
            "hUm1mL3nLwm2N4ZXXw_uFT9CUz0rEVZRwS3Q8oa3Tz-bfJHG29URD-vzOA",
          summonerName: "akaAgusto",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 216,
          wins: 129,
          losses: 133,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 902,
      perks: {
        perkIds: [8214, 8226, 8210, 8237, 8473, 8453, 5007, 5008, 5002],
        perkStyle: 8200,
        perkSubStyle: 8400,
      },
      profileIconId: 6298,
      bot: false,
      teamId: 200,
      summonerName: "Supzilla",
      summonerId: "N436bo4ixW1l6I-LhnFYrcs5fvo5Jx-R2MZs4MCaSo12JSS0",
      spell1Id: 4,
      spell2Id: 7,
      porofessorStats: {
        name: "Supzilla",
        id: "102127676",
        level: 898,
        role: {
          role: "support",
          mainRole: ["support"],
        },
        rankedStats: {
          division: null,
          gameAmount: 304,
          lp: 252,
          rank: "master",
          seasonId: "13.2",
          winrate: 51,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "master",
          seasonId: "13.1",
        },
        championStats: {
          name: "milio",
          winrate: 0,
          gameAmount: 252,
          kills: null,
          deaths: null,
          assists: null,
        },
        tags: [
          {
            title: "Bonne humeur",
            value: "good",
            details:
              "Ce joueur vient tout juste de gagner une partie. Son winrate augmente de 12 % juste après qu'il ait gagné une partie",
          },
          {
            title: "Milio casu",
            value: "bad",
            details:
              "Ce joueur a seulement joué 0 parties avec Milio durant les 30 derniers jours",
          },
        ],
      },
      masteries: {
        progression: 53.95,
        championProgression: 18.449074074074073,
        totalPoint: 5592054,
        championPoint: 7970,
        championLevel: 3,
        championToken: 0,
        chestGranded: false,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "N436bo4ixW1l6I-LhnFYrcs5fvo5Jx-R2MZs4MCaSo12JSS0",
          summonerName: "Supzilla",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 252,
          wins: 154,
          losses: 150,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 254,
      perks: {
        perkIds: [9923, 8143, 8136, 8105, 9111, 9104, 5005, 5008, 5002],
        perkStyle: 8100,
        perkSubStyle: 8000,
      },
      profileIconId: 1154,
      bot: false,
      teamId: 200,
      summonerName: "Vijebávač",
      summonerId: "dMkfzpg9RTLagplzokUW34C__R6A9qOibGtuOh_hEP9jvuY",
      spell1Id: 4,
      spell2Id: 11,
      porofessorStats: {
        name: "Vijebávač",
        id: "70411674",
        level: 67,
        role: {
          role: "jungler",
          mainRole: ["jungler"],
        },
        rankedStats: {
          division: null,
          gameAmount: 84,
          lp: 271,
          rank: "master",
          seasonId: "13.2",
          winrate: 71,
        },
        previousSeasonRankedStats: null,
        championStats: {
          name: "vi",
          winrate: 72,
          gameAmount: 74,
          kills: 10,
          deaths: 5.8,
          assists: 7,
        },
        tags: [
          {
            title: "Gros dégâts",
            value: "good",
            details:
              "Ce joueur inflige de gros dégâts par minute avec Vi ( 11.9% meilleurs joueurs)",
          },
          {
            title: "Destructeurs de tours",
            value: "good",
            details:
              "Ce joueur inflige beaucoup de dégâts aux tours ( 15.4% meilleurs dégâts aux tours avec Vi )",
          },
          {
            title: "Super Vi",
            value: "good",
            details: "Rang # 4 avec Vi % win (Classées): 71.6%",
          },
          {
            title: "OTP Vi",
            value: "good",
            details:
              "Ce joueur ne joue quasiment que Vi ( 89 % des parties des 30 derniers jours)",
          },
          {
            title: "Bonne vision",
            value: "good",
            details:
              "Ce joueur a un haut score de vision par minute quand il joue Vi (top 1.3% )",
          },
        ],
      },
      masteries: {
        progression: 6.95,
        championProgression: 64,
        totalPoint: 546681,
        championPoint: 53849,
        championLevel: 5,
        championToken: 2,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "dMkfzpg9RTLagplzokUW34C__R6A9qOibGtuOh_hEP9jvuY",
          summonerName: "Vijebávač",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 271,
          wins: 60,
          losses: 24,
          hotStreak: false,
          veteran: false,
          freshBlood: true,
          inactive: false,
        },
      ],
    },
    {
      championId: 115,
      perks: {
        perkIds: [8214, 8226, 8210, 8237, 8345, 8347, 5005, 5008, 5002],
        perkStyle: 8200,
        perkSubStyle: 8300,
      },
      profileIconId: 4596,
      bot: false,
      teamId: 200,
      summonerName: "B0LULU",
      summonerId: "HBBSjdNvVsb2MO_WjsRdoJdsYwquG0c0GScR1IuA2xv-Y_U",
      spell1Id: 3,
      spell2Id: 4,
      porofessorStats: {
        name: "B0LULU",
        id: "53116940",
        level: 844,
        role: {
          role: "mid",
          mainRole: ["mid"],
        },
        rankedStats: {
          division: null,
          gameAmount: 185,
          lp: 296,
          rank: "master",
          seasonId: "13.2",
          winrate: 53,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "challenger",
          seasonId: "13.1",
        },
        championStats: {
          name: "ziggs",
          winrate: 74,
          gameAmount: 35,
          kills: 7.7,
          deaths: 5.2,
          assists: 9.2,
        },
        tags: [
          {
            title: "Pro: Bolulu",
            value: "neutral",
            details: "Bolulu",
          },
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 2.54 kills+assists en moyenne à 10 minutes quand il joue Ziggs",
          },
          {
            title: "Gros dégâts",
            value: "good",
            details:
              "Ce joueur inflige de gros dégâts par minute avec Ziggs ( 10.6% meilleurs joueurs)",
          },
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 13.8% meilleurs CSer avec Ziggs",
          },
          {
            title: "Super Ziggs",
            value: "good",
            details: "Rang # 200 avec Ziggs % win (Classées): 74.3%",
          },
          {
            title: "Haute Participation",
            value: "good",
            details:
              "Ce joueur a une haute participation aux kills de l'équipe (est dans le top 20.3% avec Ziggs )",
          },
          {
            title: "Roam beaucoup",
            value: "neutral",
            details: "Ce joueur roams souvent quand il joue Ziggs",
          },
        ],
      },
      masteries: {
        progression: 44.79,
        championProgression: 100,
        totalPoint: 9577937,
        championPoint: 96935,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "HBBSjdNvVsb2MO_WjsRdoJdsYwquG0c0GScR1IuA2xv-Y_U",
          summonerName: "B0LULU",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 296,
          wins: 98,
          losses: 87,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
        {
          leagueId: "0d288e5e-4e4b-457a-87ae-752e3567414a",
          summonerId: "HBBSjdNvVsb2MO_WjsRdoJdsYwquG0c0GScR1IuA2xv-Y_U",
          summonerName: "B0LULU",
          queueType: "RANKED_FLEX_SR",
          tier: "EMERALD",
          rank: "II",
          leaguePoints: 74,
          wins: 10,
          losses: 9,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
  ],
} as any;
