import { LiveGame } from "./models/LiveGame";

export const persistantLiveGame = {
  gameId: 6624747244,
  gameType: "MATCHED_GAME",
  gameStartTime: 1696847735668,
  mapId: 11,
  gameLength: 806,
  platformId: "EUW1",
  gameMode: "CLASSIC",
  bannedChampions: [
    {
      pickTurn: 1,
      championId: 67,
      teamId: 100,
    },
    {
      pickTurn: 2,
      championId: 119,
      teamId: 100,
    },
    {
      pickTurn: 3,
      championId: 121,
      teamId: 100,
    },
    {
      pickTurn: 4,
      championId: 114,
      teamId: 100,
    },
    {
      pickTurn: 5,
      championId: 7,
      teamId: 100,
    },
    {
      pickTurn: 6,
      championId: 111,
      teamId: 200,
    },
    {
      pickTurn: 7,
      championId: 555,
      teamId: 200,
    },
    {
      pickTurn: 8,
      championId: 200,
      teamId: 200,
    },
    {
      pickTurn: 9,
      championId: 233,
      teamId: 200,
    },
    {
      pickTurn: 10,
      championId: 107,
      teamId: 200,
    },
  ],
  gameQueueConfigId: 420,
  participants: [
    {
      championId: 497,
      perks: {
        perkIds: [8465, 8463, 8473, 8242, 8136, 8106, 5008, 5002, 5003],
        perkStyle: 8400,
        perkSubStyle: 8100,
      },
      profileIconId: 637,
      bot: false,
      teamId: 100,
      summonerName: "MORΑTHI",
      summonerId: "ZS8Y9FeAjBVsaOng-9gdUEHwgriD-IaOOAVZTV5YmXpSLdA",
      spell1Id: 14,
      spell2Id: 4,
      porofessorStats: {
        name: "MORΑTHI",
        id: "50997777",
        level: 380,
        role: {
          role: "support",
          mainRole: ["support"],
        },
        rankedStats: {
          division: null,
          gameAmount: 90,
          lp: 449,
          rank: "master",
          seasonId: "13.2",
          winrate: 60,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "master",
          seasonId: "13.1",
        },
        championStats: {
          name: "rakan",
          winrate: 50,
          gameAmount: 4,
          kills: 1,
          deaths: 2,
          assists: 11,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 2.75 kills+assists en moyenne à 10 minutes quand il joue Rakan",
          },
          {
            title: "Bonne vision",
            value: "good",
            details:
              "Ce joueur a un haut score de vision par minute quand il joue Rakan (top 9.3% )",
          },
        ],
      },
      masteries: {
        progression: 29.64,
        championProgression: 100,
        totalPoint: 3655043,
        championPoint: 310968,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "ZS8Y9FeAjBVsaOng-9gdUEHwgriD-IaOOAVZTV5YmXpSLdA",
          summonerName: "MORΑTHI",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 449,
          wins: 54,
          losses: 36,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 59,
      perks: {
        perkIds: [8010, 9101, 9105, 8299, 8347, 8304, 5005, 5008, 5001],
        perkStyle: 8000,
        perkSubStyle: 8300,
      },
      profileIconId: 1151,
      bot: false,
      teamId: 100,
      summonerName: "rfyjpcas",
      summonerId: "zZjOjUbywRHNT5TSRP8QWBYmzFZ-AdL4C22E1sQIqryE-AoFk1fHh9SX-w",
      spell1Id: 4,
      spell2Id: 11,
      porofessorStats: {
        name: "rfyjpcas",
        id: "413459787",
        level: 77,
        role: {
          role: "jungler",
          mainRole: ["jungler"],
        },
        rankedStats: {
          division: null,
          gameAmount: 503,
          lp: 443,
          rank: "master",
          seasonId: "13.2",
          winrate: 54,
        },
        previousSeasonRankedStats: {
          division: 4,
          rank: "or",
          seasonId: "13.1",
        },
        championStats: {
          name: "jarvan iv",
          winrate: 55,
          gameAmount: 20,
          kills: 5,
          deaths: 5,
          assists: 12,
        },
        tags: [
          {
            title: "Jungler aggressif",
            value: "good",
            details:
              "Ce joueur a 3.90 kills+assists en moyenne à 10 minutes quand il joue Jarvan IV",
          },
          {
            title: "Super Jarvan IV",
            value: "good",
            details: "Rang # 109 avec Jarvan IV % win (Classées): 55.0%",
          },
        ],
      },
      masteries: {
        progression: 4.2,
        championProgression: 64,
        totalPoint: 375506,
        championPoint: 36074,
        championLevel: 5,
        championToken: 2,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId:
            "zZjOjUbywRHNT5TSRP8QWBYmzFZ-AdL4C22E1sQIqryE-AoFk1fHh9SX-w",
          summonerName: "rfyjpcas",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 443,
          wins: 272,
          losses: 231,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 516,
      perks: {
        perkIds: [8437, 8446, 8473, 8242, 8304, 8345, 5005, 5002, 5002],
        perkStyle: 8400,
        perkSubStyle: 8300,
      },
      profileIconId: 28,
      bot: false,
      teamId: 100,
      summonerName: "dennishlol",
      summonerId: "7ai4ojHHRv1vkTuMKB-wu5-eppxpANLyNjnPP_kg8oyq7EE",
      spell1Id: 12,
      spell2Id: 4,
      porofessorStats: {
        name: "dennishlol",
        id: "40096860",
        level: 461,
        role: {
          role: "top",
          mainRole: ["top"],
        },
        rankedStats: {
          division: null,
          gameAmount: 152,
          lp: 260,
          rank: "master",
          seasonId: "13.2",
          winrate: 56,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "grandmaster",
          seasonId: "13.1",
        },
        championStats: {
          name: "ornn",
          winrate: 59,
          gameAmount: 81,
          kills: 4,
          deaths: 4,
          assists: 8,
        },
        tags: [
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 15.6% meilleurs CSer avec Ornn",
          },
          {
            title: "Super Ornn",
            value: "good",
            details: "Rang # 43 avec Ornn % win (Classées): 60.0%",
          },
          {
            title: "OTP Ornn",
            value: "good",
            details:
              "Ce joueur ne joue quasiment que Ornn ( 72 % des parties des 30 derniers jours)",
          },
        ],
      },
      masteries: {
        progression: 37.46,
        championProgression: 100,
        totalPoint: 4307244,
        championPoint: 194203,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "92f10b07-3236-321c-86d0-7c9d2a0311c1",
          summonerId: "7ai4ojHHRv1vkTuMKB-wu5-eppxpANLyNjnPP_kg8oyq7EE",
          summonerName: "dennishlol",
          queueType: "RANKED_FLEX_SR",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 128,
          wins: 19,
          losses: 16,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "7ai4ojHHRv1vkTuMKB-wu5-eppxpANLyNjnPP_kg8oyq7EE",
          summonerName: "dennishlol",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 260,
          wins: 85,
          losses: 67,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 523,
      perks: {
        perkIds: [8021, 9101, 9103, 8017, 8233, 8236, 5005, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8200,
      },
      profileIconId: 5919,
      bot: false,
      teamId: 100,
      summonerName: "Fubuki Atsuya",
      summonerId: "80Gfhv6M9sq7UqPIya99AHFhpjsJxojF9MQi2z9MGjvo2rqQiV54uzyCvw",
      spell1Id: 6,
      spell2Id: 4,
      porofessorStats: {
        name: "Fubuki Atsuya",
        id: "404532746",
        level: 761,
        role: {
          role: "adc",
          mainRole: ["adc"],
        },
        rankedStats: {
          division: null,
          gameAmount: 639,
          lp: 575,
          rank: "master",
          seasonId: "13.2",
          winrate: 51,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "challenger",
          seasonId: "13.1",
        },
        championStats: {
          name: "aphelios",
          winrate: 75,
          gameAmount: 20,
          kills: 8,
          deaths: 4,
          assists: 5,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 3.60 kills+assists en moyenne à 10 minutes quand il joue Aphelios",
          },
          {
            title: "Destructeurs de tours",
            value: "good",
            details:
              "Ce joueur inflige beaucoup de dégâts aux tours ( 2.9% meilleurs dégâts aux tours avec Aphelios )",
          },
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 6.7% meilleurs CSer avec Aphelios",
          },
          {
            title: "Super Aphelios",
            value: "good",
            details: "Rang # 71 avec Aphelios % win (Classées): 75.0%",
          },
          {
            title: "Destructeur de Kai'Sa",
            value: "good",
            details:
              "Ce joueur a un winrate de 86% quand il joue Aphelios contre Kai'Sa (sur 7 parties)",
          },
          {
            title: "Bonne vision",
            value: "good",
            details:
              "Ce joueur a un haut score de vision par minute quand il joue Aphelios (top 15.9% )",
          },
          {
            title: "1ère partie",
            value: "neutral",
            details: "Première partie aujourd'hui",
          },
          {
            title: "Invader",
            value: "neutral",
            details:
              "Ce joueur invade souvent en début de partie ( 35 % des parties)",
          },
          {
            title: "Roam beaucoup",
            value: "neutral",
            details: "Ce joueur roams souvent quand il joue Aphelios",
          },
          {
            title: "Main pris par l'ennemi",
            value: "bad",
            details:
              "Le main de ce joueur ( Kai'Sa ) a été pris par l'équipe ennemie",
          },
        ],
      },
      masteries: {
        progression: 34.2,
        championProgression: 100,
        totalPoint: 8805125,
        championPoint: 527071,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId:
            "80Gfhv6M9sq7UqPIya99AHFhpjsJxojF9MQi2z9MGjvo2rqQiV54uzyCvw",
          summonerName: "Fubuki Atsuya",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 575,
          wins: 325,
          losses: 314,
          hotStreak: false,
          veteran: false,
          freshBlood: true,
          inactive: false,
        },
      ],
    },
    {
      championId: 84,
      perks: {
        perkIds: [8128, 8143, 8138, 8105, 8009, 8299, 5008, 5008, 5002],
        perkStyle: 8100,
        perkSubStyle: 8000,
      },
      profileIconId: 3804,
      bot: false,
      teamId: 100,
      summonerName: "Rob6801",
      summonerId: "tPvGDXIK_nM4CT9PKnBqNVFyYqukNhUYy_pT039gQovKAlDi",
      spell1Id: 4,
      spell2Id: 12,
      porofessorStats: {
        name: "Rob6801",
        id: "100379939",
        level: 496,
        role: {
          role: "mid",
          mainRole: ["adc"],
        },
        rankedStats: {
          division: null,
          gameAmount: 580,
          lp: 503,
          rank: "master",
          seasonId: "13.2",
          winrate: 56,
        },
        previousSeasonRankedStats: {
          division: 1,
          rank: "diamant",
          seasonId: "13.1",
        },
        championStats: {
          name: "akali",
          winrate: 69,
          gameAmount: 26,
          kills: 11,
          deaths: 3,
          assists: 4,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 2.96 kills+assists en moyenne à 10 minutes quand il joue Akali",
          },
          {
            title: "Gros dégâts",
            value: "good",
            details:
              "Ce joueur inflige de gros dégâts par minute avec Akali ( 22.4% meilleurs joueurs)",
          },
          {
            title: "Destructeurs de tours",
            value: "good",
            details:
              "Ce joueur inflige beaucoup de dégâts aux tours ( 14.7% meilleurs dégâts aux tours avec Akali )",
          },
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 3.2% meilleurs CSer avec Akali",
          },
          {
            title: "<3 Akali",
            value: "good",
            details:
              " a joué 26 parties avec Akali durant les 30 derniers jours",
          },
          {
            title: "Fill?",
            value: "neutral",
            details: "Ce joueur ne joue pas un de ses rôles habituels",
          },
        ],
      },
      masteries: {
        progression: 21.75,
        championProgression: 46.10648148148148,
        totalPoint: 3630636,
        championPoint: 19918,
        championLevel: 4,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "d28b07f0-2569-47fa-8976-824e3a500923",
          summonerId: "tPvGDXIK_nM4CT9PKnBqNVFyYqukNhUYy_pT039gQovKAlDi",
          summonerName: "Rob6801",
          queueType: "RANKED_FLEX_SR",
          tier: "GOLD",
          rank: "IV",
          leaguePoints: 22,
          wins: 35,
          losses: 33,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "tPvGDXIK_nM4CT9PKnBqNVFyYqukNhUYy_pT039gQovKAlDi",
          summonerName: "Rob6801",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 503,
          wins: 323,
          losses: 257,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 145,
      perks: {
        perkIds: [8008, 8009, 9103, 8017, 8345, 8304, 5005, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8300,
      },
      profileIconId: 5736,
      bot: false,
      teamId: 200,
      summonerName: "gzhrfhesfzhi",
      summonerId: "wYbdG1nGSBf7oWccdvGOIic3ee5z36kb76ZBahi1VPGlhEiq",
      spell1Id: 4,
      spell2Id: 6,
      porofessorStats: {
        name: "gzhrfhesfzhi",
        id: "206657713",
        level: 99,
        role: {
          role: "adc",
          mainRole: ["adc"],
        },
        rankedStats: {
          division: null,
          gameAmount: 219,
          lp: 628,
          rank: "grandmaster",
          seasonId: "13.2",
          winrate: 56,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "master",
          seasonId: "13.1",
        },
        championStats: {
          name: "kai'sa",
          winrate: 86,
          gameAmount: 7,
          kills: 9,
          deaths: 5,
          assists: 8,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 3.57 kills+assists en moyenne à 10 minutes quand il joue Kai'Sa",
          },
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 12.1% meilleurs CSer avec Kai'Sa",
          },
          {
            title: "Bon avec Kai'Sa",
            value: "good",
            details:
              "Ce joueur a un winrate de 86 % avec Kai'Sa durant les 30 derniers jours",
          },
          {
            title: "Bonne vision",
            value: "good",
            details:
              "Ce joueur a un haut score de vision par minute quand il joue Kai'Sa (top 12.1% )",
          },
          {
            title: "1ère partie",
            value: "neutral",
            details: "Première partie aujourd'hui",
          },
        ],
      },
      masteries: {
        progression: 6.86,
        championProgression: 30.504629629629633,
        totalPoint: 561070,
        championPoint: 13178,
        championLevel: 4,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "82bb1a7f-53b2-3c02-af58-458082cd4a7c",
          summonerId: "wYbdG1nGSBf7oWccdvGOIic3ee5z36kb76ZBahi1VPGlhEiq",
          summonerName: "gzhrfhesfzhi",
          queueType: "RANKED_SOLO_5x5",
          tier: "GRANDMASTER",
          rank: "I",
          leaguePoints: 628,
          wins: 122,
          losses: 97,
          hotStreak: false,
          veteran: false,
          freshBlood: true,
          inactive: false,
        },
        {
          leagueId: "4288b3ea-1ed8-4ecd-808e-75103e7657f3",
          summonerId: "wYbdG1nGSBf7oWccdvGOIic3ee5z36kb76ZBahi1VPGlhEiq",
          summonerName: "gzhrfhesfzhi",
          queueType: "RANKED_FLEX_SR",
          tier: "DIAMOND",
          rank: "IV",
          leaguePoints: 1,
          wins: 13,
          losses: 3,
          hotStreak: true,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 28,
      perks: {
        perkIds: [8112, 8143, 8138, 8105, 8233, 8236, 5008, 5008, 5002],
        perkStyle: 8100,
        perkSubStyle: 8200,
      },
      profileIconId: 1151,
      bot: false,
      teamId: 200,
      summonerName: "Gonski",
      summonerId: "SVRvTnnQT2MUst4e-129PaOnaq2cdMbYVrx9Iqa_rgriK_k_RbLiEhO9og",
      spell1Id: 4,
      spell2Id: 11,
      porofessorStats: {
        name: "Gonski",
        id: "437668957",
        level: 46,
        role: {
          role: "jungler",
          mainRole: ["jungler"],
        },
        rankedStats: {
          division: null,
          gameAmount: 172,
          lp: 410,
          rank: "master",
          seasonId: "13.2",
          winrate: 60,
        },
        previousSeasonRankedStats: null,
        championStats: {
          name: "evelynn",
          winrate: 62,
          gameAmount: 81,
          kills: 9,
          deaths: 3,
          assists: 8,
        },
        tags: [
          {
            title: "Jungler aggressif",
            value: "good",
            details:
              "Ce joueur a 4.21 kills+assists en moyenne à 10 minutes quand il joue Evelynn",
          },
          {
            title: "Super Evelynn",
            value: "good",
            details: "Rang # 86 avec Evelynn % win (Classées): 61.7%",
          },
          {
            title: "Haute Participation",
            value: "good",
            details:
              "Ce joueur a une haute participation aux kills de l'équipe (est dans le top 23.6% avec Evelynn )",
          },
        ],
      },
      masteries: {
        progression: 2.2,
        championProgression: 64,
        totalPoint: 191979,
        championPoint: 49917,
        championLevel: 5,
        championToken: 2,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId:
            "SVRvTnnQT2MUst4e-129PaOnaq2cdMbYVrx9Iqa_rgriK_k_RbLiEhO9og",
          summonerName: "Gonski",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 410,
          wins: 104,
          losses: 68,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 526,
      perks: {
        perkIds: [8351, 8306, 8316, 8347, 8473, 8242, 5007, 5002, 5003],
        perkStyle: 8300,
        perkSubStyle: 8400,
      },
      profileIconId: 539,
      bot: false,
      teamId: 200,
      summonerName: "ATK youNique",
      summonerId: "CJU-e-SSyEx8OHQCaP9WFrP1EHMfBrQzgJz7CVYD5WjPeKY",
      spell1Id: 4,
      spell2Id: 14,
      porofessorStats: {
        name: "ATK youNique",
        id: "23742161",
        level: 531,
        role: {
          role: "support",
          mainRole: ["support"],
        },
        rankedStats: {
          division: null,
          gameAmount: 39,
          lp: 130,
          rank: "master",
          seasonId: "13.2",
          winrate: 64,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "grandmaster",
          seasonId: "13.1",
        },
        championStats: {
          name: "rell",
          winrate: 57,
          gameAmount: 7,
          kills: 1,
          deaths: 6,
          assists: 16,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 4.57 kills+assists en moyenne à 10 minutes quand il joue Rell",
          },
          {
            title: "Bonne vision",
            value: "good",
            details:
              "Ce joueur a un haut score de vision par minute quand il joue Rell (top 15.4% )",
          },
          {
            title: "Invader",
            value: "neutral",
            details:
              "Ce joueur invade souvent en début de partie ( 32 % des parties)",
          },
        ],
      },
      masteries: {
        progression: 30.23,
        championProgression: 100,
        totalPoint: 4778150,
        championPoint: 67689,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "CJU-e-SSyEx8OHQCaP9WFrP1EHMfBrQzgJz7CVYD5WjPeKY",
          summonerName: "ATK youNique",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 130,
          wins: 25,
          losses: 14,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      championId: 39,
      perks: {
        perkIds: [8010, 9111, 9104, 8299, 8345, 8347, 5005, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8300,
      },
      profileIconId: 29,
      bot: false,
      teamId: 200,
      summonerName: "Giyuu zzz",
      summonerId: "Dq8esHc0GcsYPHYpY4KMAAGq6ZOwo9_-Wnot_IoWXx8tygljHStENpcj7Q",
      spell1Id: 4,
      spell2Id: 12,
      porofessorStats: {
        name: "Giyuu zzz",
        id: "380106114",
        level: 273,
        role: {
          role: "top",
          mainRole: ["mid"],
        },
        rankedStats: {
          division: null,
          gameAmount: 191,
          lp: 570,
          rank: "master",
          seasonId: "13.2",
          winrate: 53,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "challenger",
          seasonId: "13.1",
        },
        championStats: {
          name: "irelia",
          winrate: 43,
          gameAmount: 7,
          kills: 5,
          deaths: 4,
          assists: 3,
        },
        tags: [
          {
            title: "Pro: Giyuu",
            value: "neutral",
            details: "Giyuu",
          },
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 6.7% meilleurs CSer avec Irelia",
          },
          {
            title: "Bonne vision",
            value: "good",
            details:
              "Ce joueur a un haut score de vision par minute quand il joue Irelia (top 10.0% )",
          },
          {
            title: "Fill?",
            value: "neutral",
            details: "Ce joueur ne joue pas un de ses rôles habituels",
          },
        ],
      },
      masteries: {
        progression: 15.76,
        championProgression: 64,
        totalPoint: 1653341,
        championPoint: 140486,
        championLevel: 5,
        championToken: 2,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId:
            "Dq8esHc0GcsYPHYpY4KMAAGq6ZOwo9_-Wnot_IoWXx8tygljHStENpcj7Q",
          summonerName: "Giyuu zzz",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 570,
          wins: 102,
          losses: 89,
          hotStreak: false,
          veteran: false,
          freshBlood: true,
          inactive: false,
        },
      ],
    },
    {
      championId: 236,
      perks: {
        perkIds: [8005, 8009, 9103, 8014, 8345, 8304, 5005, 5008, 5001],
        perkStyle: 8000,
        perkSubStyle: 8300,
      },
      profileIconId: 539,
      bot: false,
      teamId: 200,
      summonerName: "memotherapy",
      summonerId: "gQlN1dRh8oNEprbFF-cXBQXHzcHIddAhKngj0tT8wHL6uuQ",
      spell1Id: 4,
      spell2Id: 12,
      porofessorStats: {
        name: "memotherapy",
        id: "22171385",
        level: 662,
        role: {
          role: "mid",
          mainRole: ["mid"],
        },
        rankedStats: {
          division: null,
          gameAmount: 584,
          lp: 576,
          rank: "grandmaster",
          seasonId: "13.2",
          winrate: 53,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "master",
          seasonId: "13.1",
        },
        championStats: {
          name: "lucian",
          winrate: 0,
          gameAmount: 576,
          kills: null,
          deaths: null,
          assists: null,
        },
        tags: [
          {
            title: "Pro: Memo",
            value: "neutral",
            details: "Memo",
          },
        ],
      },
      masteries: {
        progression: 31.1,
        championProgression: 100,
        totalPoint: 4085443,
        championPoint: 106680,
        championLevel: 7,
        championToken: 0,
        chestGranded: false,
      },
      leagues: [
        {
          leagueId: "82bb1a7f-53b2-3c02-af58-458082cd4a7c",
          summonerId: "gQlN1dRh8oNEprbFF-cXBQXHzcHIddAhKngj0tT8wHL6uuQ",
          summonerName: "memotherapy",
          queueType: "RANKED_SOLO_5x5",
          tier: "GRANDMASTER",
          rank: "I",
          leaguePoints: 576,
          wins: 307,
          losses: 277,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
  ],
} as any;
