import { LiveGame } from "./models/LiveGame";

export const persistantLiveGame = {
  gameId: 6717844877,
  gameType: "MATCHED_GAME",
  gameStartTime: 1702466352208,
  mapId: 11,
  gameLength: 622,
  platformId: "EUW1",
  gameMode: "CLASSIC",
  bannedChampions: [
    {
      pickTurn: 1,
      championId: 555,
      teamId: 100,
    },
    {
      pickTurn: 2,
      championId: 55,
      teamId: 100,
    },
    {
      pickTurn: 3,
      championId: 30,
      teamId: 100,
    },
    {
      pickTurn: 4,
      championId: -1,
      teamId: 100,
    },
    {
      pickTurn: 5,
      championId: 360,
      teamId: 100,
    },
    {
      pickTurn: 6,
      championId: 429,
      teamId: 200,
    },
    {
      pickTurn: 7,
      championId: 526,
      teamId: 200,
    },
    {
      pickTurn: 8,
      championId: 122,
      teamId: 200,
    },
    {
      pickTurn: 9,
      championId: 201,
      teamId: 200,
    },
    {
      pickTurn: 10,
      championId: 107,
      teamId: 200,
    },
  ],
  gameQueueConfigId: 420,
  participants: [
    {
      gameName: "Haru Wa Yuku",
      tagLine: "0216",
      puuid:
        "bMvyS8HkMNhMqt4826odN100xbxwzJcwCk2nUQGL9YnFFTjHzJACDqIbDvPEZeB5ELGeb46j8UOySw",
      championId: 53,
      perks: {
        perkIds: [8351, 8306, 8316, 8347, 8234, 8275, 5007, 5002, 5002],
        perkStyle: 8300,
        perkSubStyle: 8200,
      },
      profileIconId: 5414,
      bot: false,
      teamId: 100,
      summonerName: "Dadinho OwO",
      summonerId: "TpiCBHOoB-_t9G9T3DOTT_f4ZmRaOXKFJdjsf5hBVDtXnqy3",
      spell1Id: 14,
      spell2Id: 4,
      porofessorStats: {
        name: "Haru Wa Yuku#0216",
        id: "359834561",
        level: 116,
        role: {
          role: "support",
          mainRole: ["support"],
        },
        rankedStats: {
          division: null,
          gameAmount: 233,
          lp: 441,
          rank: "master",
          seasonId: "13.2",
          winrate: 56,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "master",
          seasonId: "13.1",
        },
        championStats: {
          name: "blitzcrank",
          winrate: 100,
          gameAmount: 1,
          kills: 0,
          deaths: 7,
          assists: 19,
        },
        tags: [
          {
            title: "1ère partie",
            value: "neutral",
            details: "Première partie aujourd'hui",
          },
          {
            title: "Blitzcrank casu",
            value: "bad",
            details:
              "Ce joueur a seulement joué 1 parties avec Blitzcrank durant les 30 derniers jours",
          },
        ],
      },
      masteries: {
        progression: 6.73,
        championProgression: 21.28009259259259,
        totalPoint: 585969,
        championPoint: 9193,
        championLevel: 3,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "TpiCBHOoB-_t9G9T3DOTT_f4ZmRaOXKFJdjsf5hBVDtXnqy3",
          summonerName: "Dadinho OwO",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 441,
          wins: 131,
          losses: 102,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      gameName: "Poweh",
      tagLine: "dog",
      puuid:
        "bMvyS8HkMNhMqt4826odN100xbxwzJcwCk2nUQGL9YnFFTjHzJACDqIbDvPEZeB5ELGeb46j8UOySw",
      championId: 157,
      perks: {
        perkIds: [8008, 9111, 9104, 8299, 8473, 8242, 5005, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8400,
      },
      profileIconId: 744,
      bot: false,
      teamId: 100,
      summonerName: "9955",
      summonerId: "JMOX84E-hkrEdMitdcsY1EHyCrAND6Ofdfe8poAatQaGYMA",
      spell1Id: 12,
      spell2Id: 4,
      porofessorStats: {
        name: "Poweh#dog",
        id: "52324433",
        level: 587,
        role: {
          role: "top",
          mainRole: ["top"],
        },
        rankedStats: {
          division: null,
          gameAmount: 453,
          lp: 331,
          rank: "master",
          seasonId: "13.2",
          winrate: 52,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "master",
          seasonId: "13.1",
        },
        championStats: {
          name: "yasuo",
          winrate: 39,
          gameAmount: 23,
          kills: 6.8,
          deaths: 7.4,
          assists: 5,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 2.91 kills+assists en moyenne à 10 minutes quand il joue Yasuo",
          },
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 13.8% meilleurs CSer avec Yasuo",
          },
          {
            title: "<3 Yasuo",
            value: "good",
            details:
              " a joué 23 parties avec Yasuo durant les 30 derniers jours",
          },
          {
            title: "Invader",
            value: "neutral",
            details:
              "Ce joueur invade souvent en début de partie ( 35 % des parties)",
          },
          {
            title: "Split Pusher",
            value: "neutral",
            details: "Ce joueur split push très souvent quand il joue Yasuo",
          },
        ],
      },
      masteries: {
        progression: 48.08,
        championProgression: 100,
        totalPoint: 6803565,
        championPoint: 680607,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "208763a2-3203-41a0-95a1-c5a99e13eabc",
          summonerId: "JMOX84E-hkrEdMitdcsY1EHyCrAND6Ofdfe8poAatQaGYMA",
          summonerName: "9955",
          queueType: "RANKED_FLEX_SR",
          tier: "DIAMOND",
          rank: "III",
          leaguePoints: 35,
          wins: 34,
          losses: 34,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "JMOX84E-hkrEdMitdcsY1EHyCrAND6Ofdfe8poAatQaGYMA",
          summonerName: "9955",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 331,
          wins: 237,
          losses: 216,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
        {
          summonerId: "JMOX84E-hkrEdMitdcsY1EHyCrAND6Ofdfe8poAatQaGYMA",
          summonerName: "9955",
          queueType: "CHERRY",
          leaguePoints: 0,
          wins: 5,
          losses: 3,
          hotStreak: false,
          veteran: false,
          freshBlood: true,
          inactive: false,
        },
      ],
    },
    {
      gameName: "F10 Demon Arc",
      tagLine: "EUW",
      puuid:
        "bMvyS8HkMNhMqt4826odN100xbxwzJcwCk2nUQGL9YnFFTjHzJACDqIbDvPEZeB5ELGeb46j8UOySw",
      championId: 64,
      perks: {
        perkIds: [8010, 9111, 9104, 8014, 8347, 8304, 5005, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8300,
      },
      profileIconId: 7,
      bot: false,
      teamId: 100,
      summonerName: "F10 Demon Arc",
      summonerId: "mJdp28COtj7s61FcKdieC6BPnAMDoMlb_GAsklyoz7Z5uSEfvPi5jcpCeg",
      spell1Id: 4,
      spell2Id: 11,
      porofessorStats: {
        name: "F10 Demon Arc#EUW",
        id: "399329967",
        level: 88,
        role: {
          role: "jungler",
          mainRole: ["jungler"],
        },
        rankedStats: {
          division: null,
          gameAmount: 676,
          lp: 401,
          rank: "master",
          seasonId: "13.2",
          winrate: 55,
        },
        previousSeasonRankedStats: null,
        championStats: {
          name: "lee sin",
          winrate: 59,
          gameAmount: 138,
          kills: 7.6,
          deaths: 4,
          assists: 9.6,
        },
        tags: [
          {
            title: "Jungler aggressif",
            value: "good",
            details:
              "Ce joueur a 3.62 kills+assists en moyenne à 10 minutes quand il joue Lee Sin",
          },
          {
            title: "Super Lee Sin",
            value: "good",
            details: "Rang # 401 avec Lee Sin % win (Classées): 59.4%",
          },
          {
            title: "Voleur",
            value: "good",
            details:
              "Ce joueur vole souvent l'hérald, le dragon ou le baron ( 0.12 par match) lorsqu'il joue Lee Sin",
          },
          {
            title: "Bonne vision",
            value: "good",
            details:
              "Ce joueur a un haut score de vision par minute quand il joue Lee Sin (top 19.5% )",
          },
        ],
      },
      masteries: {
        progression: 2.57,
        championProgression: 64,
        totalPoint: 405909,
        championPoint: 231780,
        championLevel: 5,
        championToken: 2,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId:
            "mJdp28COtj7s61FcKdieC6BPnAMDoMlb_GAsklyoz7Z5uSEfvPi5jcpCeg",
          summonerName: "F10 Demon Arc",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 401,
          wins: 369,
          losses: 307,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      gameName: "Vizzpers",
      tagLine: "8177",
      puuid:
        "bMvyS8HkMNhMqt4826odN100xbxwzJcwCk2nUQGL9YnFFTjHzJACDqIbDvPEZeB5ELGeb46j8UOySw",
      championId: 222,
      perks: {
        perkIds: [8008, 8009, 9104, 8017, 8233, 8236, 5005, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8200,
      },
      profileIconId: 0,
      bot: false,
      teamId: 100,
      summonerName: "Hans SamC",
      summonerId: "nXDjLQkzF_bu9U7Po9UDF7uOIaglCEv08KfhP5h0mPMv_ks",
      spell1Id: 4,
      spell2Id: 6,
      porofessorStats: {
        name: "Vizzpers#8177",
        id: "45469485",
        level: 747,
        role: {
          role: "adc",
          mainRole: ["adc"],
        },
        rankedStats: {
          division: null,
          gameAmount: 602,
          lp: 497,
          rank: "master",
          seasonId: "13.2",
          winrate: 52,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "grandmaster",
          seasonId: "13.1",
        },
        championStats: {
          name: "jinx",
          winrate: 58,
          gameAmount: 36,
          kills: 7.8,
          deaths: 4.3,
          assists: 6.4,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 2.53 kills+assists en moyenne à 10 minutes quand il joue Jinx",
          },
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 11.9% meilleurs CSer avec Jinx",
          },
          {
            title: "Super Jinx",
            value: "good",
            details: "Rang # 311 avec Jinx % win (Classées): 58.3%",
          },
          {
            title: "1ère partie",
            value: "neutral",
            details: "Première partie aujourd'hui",
          },
        ],
      },
      masteries: {
        progression: 44.27,
        championProgression: 100,
        totalPoint: 6360613,
        championPoint: 98685,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "nXDjLQkzF_bu9U7Po9UDF7uOIaglCEv08KfhP5h0mPMv_ks",
          summonerName: "Hans SamC",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 497,
          wins: 314,
          losses: 288,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      gameName: "Jakoo",
      tagLine: "Broke",
      puuid:
        "bMvyS8HkMNhMqt4826odN100xbxwzJcwCk2nUQGL9YnFFTjHzJACDqIbDvPEZeB5ELGeb46j8UOySw",
      championId: 134,
      perks: {
        perkIds: [8230, 8226, 8210, 8236, 8347, 8316, 5005, 5008, 5002],
        perkStyle: 8200,
        perkSubStyle: 8300,
      },
      profileIconId: 6316,
      bot: false,
      teamId: 100,
      summonerName: "Jakoo v9",
      summonerId: "FjfhPLS5ZIHNJYli--1jBNhefKkAuuJkxXlnbF4KN26P5bE",
      spell1Id: 4,
      spell2Id: 12,
      porofessorStats: {
        name: "Jakoo#Broke",
        id: "51341536",
        level: 841,
        role: {
          role: "mid",
          mainRole: ["mid"],
        },
        rankedStats: {
          division: null,
          gameAmount: 202,
          lp: 519,
          rank: "master",
          seasonId: "13.2",
          winrate: 56,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "grandmaster",
          seasonId: "13.1",
        },
        championStats: {
          name: "syndra",
          winrate: 89,
          gameAmount: 9,
          kills: 8.4,
          deaths: 2.7,
          assists: 6.6,
        },
        tags: [
          {
            title: "Gros dégâts",
            value: "good",
            details:
              "Ce joueur inflige de gros dégâts par minute avec Syndra ( 24.2% meilleurs joueurs)",
          },
          {
            title: "Destructeurs de tours",
            value: "good",
            details:
              "Ce joueur inflige beaucoup de dégâts aux tours ( 10.4% meilleurs dégâts aux tours avec Syndra )",
          },
          {
            title: "Bon CSer",
            value: "good",
            details: "Ce joueur est dans les 12.1% meilleurs CSer avec Syndra",
          },
          {
            title: "Super Syndra",
            value: "good",
            details: "Rang # 836 avec Syndra % win (Classées): 88.9%",
          },
          {
            title: "Laner intuable",
            value: "good",
            details:
              "Ce joueur a en moyenne seulement 0.44 morts à 10 minutes quand il joue Syndra",
          },
          {
            title: "1ère partie",
            value: "neutral",
            details: "Première partie aujourd'hui",
          },
          {
            title: "Roam beaucoup",
            value: "neutral",
            details: "Ce joueur roams souvent quand il joue Syndra",
          },
          {
            title: "Split Pusher",
            value: "neutral",
            details: "Ce joueur split push très souvent quand il joue Syndra",
          },
        ],
      },
      masteries: {
        progression: 63.53,
        championProgression: 100,
        totalPoint: 7249878,
        championPoint: 129167,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          summonerId: "FjfhPLS5ZIHNJYli--1jBNhefKkAuuJkxXlnbF4KN26P5bE",
          summonerName: "Jakoo v9",
          queueType: "CHERRY",
          leaguePoints: 0,
          wins: 3,
          losses: 2,
          hotStreak: false,
          veteran: false,
          freshBlood: true,
          inactive: false,
        },
        {
          leagueId: "dd8c1ff7-2f2c-3629-8e30-5d7225926a7f",
          summonerId: "FjfhPLS5ZIHNJYli--1jBNhefKkAuuJkxXlnbF4KN26P5bE",
          summonerName: "Jakoo v9",
          queueType: "RANKED_FLEX_SR",
          tier: "CHALLENGER",
          rank: "I",
          leaguePoints: 502,
          wins: 123,
          losses: 106,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "FjfhPLS5ZIHNJYli--1jBNhefKkAuuJkxXlnbF4KN26P5bE",
          summonerName: "Jakoo v9",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 519,
          wins: 114,
          losses: 88,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      gameName: "A Little Halfgod",
      tagLine: "EUW",
      puuid:
        "bMvyS8HkMNhMqt4826odN100xbxwzJcwCk2nUQGL9YnFFTjHzJACDqIbDvPEZeB5ELGeb46j8UOySw",
      championId: 58,
      perks: {
        perkIds: [8010, 9111, 9104, 8299, 8473, 8401, 5005, 5008, 5003],
        perkStyle: 8000,
        perkSubStyle: 8400,
      },
      profileIconId: 744,
      bot: false,
      teamId: 200,
      summonerName: "A Little Halfgod",
      summonerId: "4R3yW-Yy6FSetaHwtYRZlRSV5lX-vn04Qnm1qB_b5DskYpV_",
      spell1Id: 4,
      spell2Id: 14,
      porofessorStats: {
        name: "A Little Halfgod#EUW",
        id: "105811153",
        level: 394,
        role: {
          role: "top",
          mainRole: ["top"],
        },
        rankedStats: {
          division: null,
          gameAmount: 295,
          lp: 150,
          rank: "master",
          seasonId: "13.2",
          winrate: 54,
        },
        previousSeasonRankedStats: {
          division: 2,
          rank: "diamant",
          seasonId: "13.1",
        },
        championStats: {
          name: "renekton",
          winrate: 100,
          gameAmount: 1,
          kills: 3,
          deaths: 7,
          assists: 3,
        },
        tags: [
          {
            title: "1ère partie",
            value: "neutral",
            details: "Première partie aujourd'hui",
          },
        ],
      },
      masteries: {
        progression: 26.23,
        championProgression: 50,
        totalPoint: 2536466,
        championPoint: 22703,
        championLevel: 5,
        championToken: 0,
        chestGranded: false,
      },
      leagues: [
        {
          leagueId: "4be660d8-9515-4a83-9e21-415ca5bfb407",
          summonerId: "4R3yW-Yy6FSetaHwtYRZlRSV5lX-vn04Qnm1qB_b5DskYpV_",
          summonerName: "A Little Halfgod",
          queueType: "RANKED_FLEX_SR",
          tier: "SILVER",
          rank: "IV",
          leaguePoints: 74,
          wins: 5,
          losses: 3,
          hotStreak: false,
          veteran: false,
          freshBlood: true,
          inactive: false,
        },
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "4R3yW-Yy6FSetaHwtYRZlRSV5lX-vn04Qnm1qB_b5DskYpV_",
          summonerName: "A Little Halfgod",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 150,
          wins: 160,
          losses: 135,
          hotStreak: true,
          veteran: false,
          freshBlood: true,
          inactive: false,
        },
      ],
    },
    {
      gameName: "Daglas fangirl",
      tagLine: "EUW",
      puuid:
        "bMvyS8HkMNhMqt4826odN100xbxwzJcwCk2nUQGL9YnFFTjHzJACDqIbDvPEZeB5ELGeb46j8UOySw",
      championId: 39,
      perks: {
        perkIds: [8008, 9111, 9104, 8299, 8345, 8347, 5005, 5008, 5003],
        perkStyle: 8000,
        perkSubStyle: 8300,
      },
      profileIconId: 1105,
      bot: false,
      teamId: 200,
      summonerName: "Daglas fangirl",
      summonerId: "nAC_ZPxYCIHZfzKc6H0cleWMFUOd2FONHfdUCPHQd8w_L68",
      spell1Id: 12,
      spell2Id: 4,
      porofessorStats: {
        name: "Daglas fangirl#EUW",
        id: "93077792",
        level: 410,
        role: {
          role: "mid",
          mainRole: ["mid"],
        },
        rankedStats: {
          division: null,
          gameAmount: 116,
          lp: 57,
          rank: "master",
          seasonId: "13.2",
          winrate: 57,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "challenger",
          seasonId: "13.1",
        },
        championStats: {
          name: "irelia",
          winrate: 100,
          gameAmount: 1,
          kills: 10,
          deaths: 1,
          assists: 2,
        },
        tags: [
          {
            title: "Pro: Czajek",
            value: "neutral",
            details: "Czajek (Vitality.Bee)",
          },
          {
            title: "1ère partie",
            value: "neutral",
            details: "Première partie aujourd'hui",
          },
        ],
      },
      masteries: {
        progression: 26.96,
        championProgression: 98,
        totalPoint: 2239636,
        championPoint: 52390,
        championLevel: 6,
        championToken: 3,
        chestGranded: true,
      },
      leagues: [
        {
          summonerId: "nAC_ZPxYCIHZfzKc6H0cleWMFUOd2FONHfdUCPHQd8w_L68",
          summonerName: "Daglas fangirl",
          queueType: "CHERRY",
          leaguePoints: 0,
          wins: 5,
          losses: 1,
          hotStreak: false,
          veteran: false,
          freshBlood: true,
          inactive: false,
        },
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "nAC_ZPxYCIHZfzKc6H0cleWMFUOd2FONHfdUCPHQd8w_L68",
          summonerName: "Daglas fangirl",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 57,
          wins: 66,
          losses: 50,
          hotStreak: false,
          veteran: false,
          freshBlood: true,
          inactive: false,
        },
      ],
    },
    {
      gameName: "LOVEGOONiNG88",
      tagLine: "DADDY",
      puuid:
        "bMvyS8HkMNhMqt4826odN100xbxwzJcwCk2nUQGL9YnFFTjHzJACDqIbDvPEZeB5ELGeb46j8UOySw",
      championId: 16,
      perks: {
        perkIds: [8214, 8226, 8210, 8237, 8429, 8451, 5008, 5008, 5001],
        perkStyle: 8200,
        perkSubStyle: 8400,
      },
      profileIconId: 7,
      bot: false,
      teamId: 200,
      summonerName: "LOVEGOONiNG88",
      summonerId: "UV1Z0OxzvDCxywXGCusYDQ9McjctLH7EphQVN3LaoR1L1mSlTN2CRN9sbQ",
      spell1Id: 4,
      spell2Id: 7,
      porofessorStats: {
        name: "LOVEGOONiNG88#DADDY",
        id: "397792593",
        level: 49,
        role: {
          role: "support",
          mainRole: ["mid"],
        },
        rankedStats: {
          division: null,
          gameAmount: 206,
          lp: 274,
          rank: "master",
          seasonId: "13.2",
          winrate: 55,
        },
        previousSeasonRankedStats: null,
        championStats: {
          name: "soraka",
          winrate: 0,
          gameAmount: 274,
          kills: null,
          deaths: null,
          assists: null,
        },
        tags: [
          {
            title: "Fill?",
            value: "neutral",
            details: "Ce joueur ne joue pas un de ses rôles habituels",
          },
          {
            title: "OTP Qiyana",
            value: "neutral",
            details:
              "Ce joueur ne joue quasiment que Qiyana ( 73 % des parties des 30 derniers jours)",
          },
          {
            title: "Débutant avec Soraka",
            value: "bad",
            details: "Ce joueur n'a quasiment jamais joué Soraka",
          },
        ],
      },
      masteries: {
        progression: 0.83,
        championProgression: 0,
        totalPoint: 123410,
        championPoint: 0,
        championLevel: 0,
        championToken: 0,
        chestGranded: false,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId:
            "UV1Z0OxzvDCxywXGCusYDQ9McjctLH7EphQVN3LaoR1L1mSlTN2CRN9sbQ",
          summonerName: "LOVEGOONiNG88",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 274,
          wins: 114,
          losses: 92,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      gameName: "Uciu",
      tagLine: "EUW",
      puuid:
        "bMvyS8HkMNhMqt4826odN100xbxwzJcwCk2nUQGL9YnFFTjHzJACDqIbDvPEZeB5ELGeb46j8UOySw",
      championId: 147,
      perks: {
        perkIds: [8214, 8226, 8210, 8236, 8009, 8014, 5005, 5008, 5002],
        perkStyle: 8200,
        perkSubStyle: 8000,
      },
      profileIconId: 1665,
      bot: false,
      teamId: 200,
      summonerName: "Uciu",
      summonerId: "UUqBsr-O9FRnCbMQ7J6tUQov6bYVKEblHwX4xK6HG7Ea9oA",
      spell1Id: 12,
      spell2Id: 4,
      porofessorStats: {
        name: "Uciu#EUW",
        id: "46819037",
        level: 401,
        role: {
          role: "adc",
          mainRole: ["mid"],
        },
        rankedStats: {
          division: null,
          gameAmount: 864,
          lp: 368,
          rank: "master",
          seasonId: "13.2",
          winrate: 51,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "master",
          seasonId: "13.1",
        },
        championStats: {
          name: "séraphine",
          winrate: 67,
          gameAmount: 12,
          kills: 3.1,
          deaths: 5.5,
          assists: 9.7,
        },
        tags: [
          {
            title: "Laner aggressif",
            value: "good",
            details:
              "Ce joueur a 2.50 kills+assists en moyenne à 10 minutes quand il joue Séraphine",
          },
          {
            title: "Destructeurs de tours",
            value: "good",
            details:
              "Ce joueur inflige beaucoup de dégâts aux tours ( 11.3% meilleurs dégâts aux tours avec Séraphine )",
          },
          {
            title: "Bon CSer",
            value: "good",
            details:
              "Ce joueur est dans les 0.9% meilleurs CSer avec Séraphine",
          },
          {
            title: "Fill?",
            value: "neutral",
            details: "Ce joueur ne joue pas un de ses rôles habituels",
          },
          {
            title: "Roam beaucoup",
            value: "neutral",
            details: "Ce joueur roams souvent quand il joue Séraphine",
          },
          {
            title: "Mauvaise vision",
            value: "bad",
            details:
              "Ce joueur a un mauvais score de vision par minute quand il joue Séraphine (pire 11.3% )",
          },
        ],
      },
      masteries: {
        progression: 20.01,
        championProgression: 64,
        totalPoint: 3758143,
        championPoint: 139848,
        championLevel: 5,
        championToken: 2,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "UUqBsr-O9FRnCbMQ7J6tUQov6bYVKEblHwX4xK6HG7Ea9oA",
          summonerName: "Uciu",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 368,
          wins: 441,
          losses: 423,
          hotStreak: false,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
    {
      gameName: "Bambii",
      tagLine: "JNG",
      puuid:
        "bMvyS8HkMNhMqt4826odN100xbxwzJcwCk2nUQGL9YnFFTjHzJACDqIbDvPEZeB5ELGeb46j8UOySw",
      championId: 234,
      perks: {
        perkIds: [8010, 9111, 9104, 8014, 8347, 8304, 5005, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8300,
      },
      profileIconId: 4794,
      bot: false,
      teamId: 200,
      summonerName: "KT Cuzzz",
      summonerId: "zuLD4V1t2sd4maIIEfexP0WaLtzbrpMgQidwp08q-qJ_kss",
      spell1Id: 4,
      spell2Id: 11,
      porofessorStats: {
        name: "Bambii#JNG",
        id: "77901223",
        level: 826,
        role: {
          role: "jungler",
          mainRole: ["jungler"],
        },
        rankedStats: {
          division: null,
          gameAmount: 539,
          lp: 534,
          rank: "master",
          seasonId: "13.2",
          winrate: 53,
        },
        previousSeasonRankedStats: {
          division: null,
          rank: "grandmaster",
          seasonId: "13.1",
        },
        championStats: {
          name: "viego",
          winrate: 50,
          gameAmount: 16,
          kills: 8,
          deaths: 5.1,
          assists: 6.9,
        },
        tags: [
          {
            title: "Jungler aggressif",
            value: "good",
            details:
              "Ce joueur a 2.88 kills+assists en moyenne à 10 minutes quand il joue Viego",
          },
          {
            title: "Voleur",
            value: "good",
            details:
              "Ce joueur vole souvent l'hérald, le dragon ou le baron ( 0.13 par match) lorsqu'il joue Viego",
          },
        ],
      },
      masteries: {
        progression: 43.75,
        championProgression: 100,
        totalPoint: 7304786,
        championPoint: 232466,
        championLevel: 7,
        championToken: 0,
        chestGranded: true,
      },
      leagues: [
        {
          leagueId: "1d9e01c8-9617-45ba-8bd6-89149802cea3",
          summonerId: "zuLD4V1t2sd4maIIEfexP0WaLtzbrpMgQidwp08q-qJ_kss",
          summonerName: "KT Cuzzz",
          queueType: "RANKED_FLEX_SR",
          tier: "EMERALD",
          rank: "II",
          leaguePoints: 75,
          wins: 56,
          losses: 56,
          hotStreak: false,
          veteran: false,
          freshBlood: false,
          inactive: false,
        },
        {
          leagueId: "f520b994-53f4-31f5-8379-068c7f291507",
          summonerId: "zuLD4V1t2sd4maIIEfexP0WaLtzbrpMgQidwp08q-qJ_kss",
          summonerName: "KT Cuzzz",
          queueType: "RANKED_SOLO_5x5",
          tier: "MASTER",
          rank: "I",
          leaguePoints: 534,
          wins: 286,
          losses: 253,
          hotStreak: true,
          veteran: true,
          freshBlood: false,
          inactive: false,
        },
      ],
    },
  ],
};
